workflows:
  android-debug-apk:
    name: GeTech - APK Debug
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      java: 21
    scripts:
      - name: Build APK nativo
        script: |
          chmod +x gradlew
          ./gradlew clean assembleDebug --stacktrace --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
